main/urls.py
from django.urls import path
from main.views import show_main, create_product, show_xml, show_json, show_xml_by_id, show_json_by_id, register, login_user, logout_user, edit_product
from main.views import delete_product, add_product_ajax, create_product_flutter

app_name = 'main'

urlpatterns = [
    path('', show_main, name='show_main'),
    path('create-product', create_product, name='create_product'),
    path('xml/', show_xml, name='show_xml'),
    path('json/', show_json, name='show_json'),
    path('xml/<str:id>/', show_xml_by_id, name='show_xml_by_id'),
    path('json/<str:id>/', show_json_by_id, name='show_json_by_id'),
    path('register/', register, name='register'),
    path('login/', login_user, name='login'),
    path('logout/', logout_user, name='logout'),
    path('edit/<uuid:id>', edit_product, name='edit'),
    path('delete/<uuid:id>', delete_product, name='delete'),
    path('add-product-ajax', add_product_ajax, name='add_product_ajax'),
    path('create-flutter/', create_product_flutter, name='create_product_flutter'),
]

toko_wee/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('auth/', include('authentication.urls')),
    path('', include('main.urls')),
]

main/models.py
from django.db import models
import uuid
from django.contrib.auth.models import User
from django.core.validators import MinValueValidator
    
class Product(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    itemName = models.CharField(max_length=255)
    itemDescription = models.TextField()
    itemPrice = models.DecimalField(max_digits=10, decimal_places=2, validators=[MinValueValidator(0.0)])
    itemStock = models.IntegerField(validators=[MinValueValidator(0)])
    itemImageURL = models.URLField(default='https://i.imgur.com/tGd7up6.jpeg')
    itemCategory = models.TextField()

    def __str__(self):
        return self.itemName

main/forms.py
from django.forms import ModelForm
from main.models import Product
from django.utils.html import strip_tags

class ProductForm(ModelForm):
    class Meta:
        model = Product
        fields = ['itemName', 'itemDescription', 'itemPrice', 'itemStock', 'itemCategory', 'itemImageURL']

    def clean_itemName(self):
        itemName = self.cleaned_data["itemName"]
        return strip_tags(itemName)
    
    def clean_itemDescription(self):
        itemDescription = self.cleaned_data["itemDescription"]
        return strip_tags(itemDescription)
    
    def clean_itemPrice(self):
        itemPrice = self.cleaned_data["itemPrice"]
        return strip_tags(itemPrice)
    
    def clean_itemStock(self):
        itemStock = self.cleaned_data["itemStock"]
        return strip_tags(itemStock)
    
    def clean_itemCategory(self):
        itemCategory = self.cleaned_data["itemCategory"]
        return strip_tags(itemCategory)
    
    def clean_itemImageURL(self):
        itemImageURL = self.cleaned_data["itemImageURL"]
        return strip_tags(itemImageURL)

main/views.py
from django.shortcuts import render, redirect
from main.forms import ProductForm
from main.models import Product
from django.http import HttpResponse, HttpResponseRedirect
from django.core import serializers
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
import datetime
from django.urls import reverse
from django.views.decorators.csrf import csrf_exempt
from django.views.decorators.http import require_POST
from django.utils.html import strip_tags
import json
from django.http import JsonResponse

@login_required(login_url='/login')
def show_main(request):
    context = {
        'last_login': request.COOKIES.get('last_login', 'Never'),
        'username': request.user.username
        }

    return render(request, "main.html", context)

def create_product(request):
    form = ProductForm(request.POST or None)
    context = {
        'form': form,
        'username': request.user.username 
    }
    if form.is_valid() and request.method == 'POST':
        product_entry = form.save(commit=False)
        product_entry.user = request.user
        product_entry.save()
        return redirect('main:show_main')
    
    return render(request, "create_product.html", context)


def show_xml(request):
    data = Product.objects.filter(user=request.user)
    return HttpResponse(serializers.serialize("xml", data), content_type="application/xml")

def show_json(request):
    data = Product.objects.filter(user=request.user)
    return HttpResponse(serializers.serialize("json", data), content_type="application/json")

def show_xml_by_id(request, id):
    data = Product.objects.filter(pk=id)
    return HttpResponse(serializers.serialize("xml", data), content_type="application/xml")

def show_json_by_id(request, id):
    data = Product.objects.filter(pk=id)
    return HttpResponse(serializers.serialize("json", data), content_type="application/json")

def register(request):
    form = UserCreationForm()

    if request.method == "POST":
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'Your account has been successfully registered!')
            return redirect('main:login')
    context = {'form':form}
    return render(request, 'create_account.html', context)

def login_user(request):
    if request.method == 'POST':
        form = AuthenticationForm(data=request.POST)

        if form.is_valid():
            user = form.get_user()
            login(request, user)
            response = HttpResponseRedirect(reverse("main:show_main"))
            response.set_cookie('last_login', str(datetime.datetime.now()))
            return response
        else:
            messages.error(request, "Invalid username or password. Please try again.")
    else:
        form = AuthenticationForm(request)

    context = {'form': form}
    return render(request, 'login.html', context)

def logout_user(request):
    logout(request)
    response = HttpResponseRedirect(reverse('main:login'))
    response.delete_cookie('last_login')
    return response

def edit_product(request, id):
    product = Product.objects.get(pk=id)
    form = ProductForm(request.POST or None, instance=product)

    context = {
        'form': form,
        'username': request.user.username
    }

    if form.is_valid() and request.method == "POST":
        form.save()
        return HttpResponseRedirect(reverse('main:show_main'))

    return render(request, "edit_product.html", context)


def delete_product(request, id):
    product = Product.objects.get(pk = id)
    product.delete()
    return HttpResponseRedirect(reverse('main:show_main'))

@csrf_exempt
@require_POST
def add_product_ajax(request):
    itemName = strip_tags(request.POST.get("itemName"))
    itemDescription = strip_tags(request.POST.get("itemDescription"))
    itemPrice = strip_tags(request.POST.get("itemPrice"))
    itemStock = strip_tags(request.POST.get("itemStock"))
    itemImageURL = strip_tags(request.POST.get("itemImageURL"))
    itemCategory = strip_tags(request.POST.get("itemCategory"))
    user = request.user

    new_product = Product(
        itemName = itemName, itemDescription = itemDescription,
        itemPrice = itemPrice, itemStock = itemStock,
        itemImageURL = itemImageURL, itemCategory = itemCategory,
        user = user
    )

    new_product.save()

    return HttpResponse(b"CREATED", status=201)

@csrf_exempt
def create_product_flutter(request):
    if request.method == 'POST':

        data = json.loads(request.body)
        new_product = Product.objects.create(
            user=request.user,
            itemName=data["itemName"],
            itemPrice=int(data["itemPrice"]),
            itemDescription=data["itemDescription"],
            itemStock=int(data["itemStock"]),
            itemCategory=data["itemCategory"],
        )

        new_product.save()

        return JsonResponse({"status": "success"}, status=200)
    else:
        return JsonResponse({"status": "error"}, status=401)

main/templates/create_account.html
{% extends 'base.html' %}

{% block meta %}
<title>Register Page</title>
{% endblock meta %}

{% block content %}

<style>
  body {
    margin: 0;
    padding: 0;
    background-color: #000;
    color: #fff;
    font-family: 'Poppins', sans-serif;
  }

  .login {
    background-color: rgb(25, 25, 25);
    padding: 30px;
    margin: 0 auto;
    border-radius: 15px;
    max-width: 500px;
    text-align: center;
  }

  .login h1 {
    color: antiquewhite;
  }

  .form-group {
    margin-bottom: 20px;
    text-align: left;
  }

  .form-group label {
    display: block;
    margin-bottom: 5px;
    color: antiquewhite;
  }

  .form-group input[type="text"],
  .form-group input[type="email"],
  .form-group input[type="password"] {
    background: rgb(55, 65, 81);
    width: 100%;
    padding: 10px;
    border-radius: 5px;
    border: 1px solid #ccc;
    box-sizing: border-box;
  }

  .btn {
    color: antiquewhite;
    border-radius: 15px;
    padding: 10px 20px;
    background-color: rgb(35, 37, 37);
    border: none;
    margin-top: 20px;
    margin-left: 175px;
    cursor: pointer;
    transition: transform 0.5s ease;
  }

  .btn:hover {
    transform: scale(1.03);
  }

  ul {
    margin-top: 15px;
    list-style: none;
    padding-left: 0;
  }

  ul li {
    color: red;
  }
</style>

<div style="margin-top: 50px;" class="login">
  <img src="https://i.imgur.com/oTUETWx.png" class="mb-6 mx-auto">
  <form method="POST">
    {% csrf_token %}
    <div class="form-group">
      <label for="username">Username</label>
      <input type="text" name="username" id="username" placeholder="Username" required>
    </div>
  
    <div class="form-group">
      <label for="password1">Password</label>
      <input type="password" name="password1" id="password1" placeholder="Password" required>
    </div>
    
    <div class="form-group">
      <label for="password2">Confirm Password</label>
      <input type="password" name="password2" id="password2" placeholder="Confirm Password" required>
    </div>
    
    <div class="form-group">
      <input class="btn" type="submit" name="submit" value="Register" />
    </div>
  </form>

  {% if messages %}
  <ul>
    {% for message in messages %}
    <li>{{ message }}</li>
    {% endfor %}
  </ul>
  {% endif %}
</div>

{% endblock content %}

main/templates/create_product.html
{% extends 'base.html' %} 
{% block content %}
<head>
    <style>
        body {
            margin: 0;
            padding: 0;
            background-color: #000;
            color: antiquewhite;
            font-family: 'Poppins', sans-serif;
        }
        .main-container{
          padding: 20px;
          background-color: #151515;
          max-width: 1200px;
          text-align: center;
          border-radius: 25px;
          margin-top: 20px;
          margin-left: 50px;
        }
        .forms {
          display: flex;
          margin-left: 325px;
        }
        td {
          padding-top: 10px;
          padding-left: 20px;
        }
    </style>
</head> 

<body>
    <div class="main-container">
      <h3 style="text-align: center;">Add Your New Product</h3>
      <hr>
      <div class="forms">
        <form method="POST">
          {% csrf_token %}
          <table>
            {{ form.as_table }}
            <tr>
              <td></td>
              <td>
                <input type="submit" value="Add the product!" />
              </td> 
            </tr>
          </table>
        </form>
      </div>
    </div>
    <h5 style="text-align: center; margin-top: 50px;">© Toko Wee | All rights Reserved.</h5>
    <h5 style="text-align: center;">Nama: Arzaka Raffan Mawardi | NPM: 2306152393 | Kelas: PBP D</h5>
</body>


{% endblock %}

main/templates/edit_product.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
{% include 'navbar.html' %}
<head>
    <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@400;600&display=swap" rel="stylesheet">
    <style>
        body {
            margin: 0;
            padding: 0;
            background-color: #000;
            color: antiquewhite;
            font-family: 'Poppins', sans-serif;
        }
        .bg-black {
            min-height: 100vh; 
            display: flex;
            flex-direction: column; 
            align-items: center; 
            justify-content: center; 
            overflow: hidden; 
        }
        .main-container {
            padding: 20px;
            background-color: #151515;
            max-width: 800px;
            text-align: center;
            border-radius: 25px;
            margin: 20px;
        }
        .forms {
            display: flex;
            justify-content: center; 
            margin-top: 20px;
        }
        td {
            padding-top: 10px;
            padding-left: 20px;
        }
        input[type="text"], 
        input[type="number"], 
        input[type="email"], 
        input[type="password"], 
        input[type="url"],
        textarea {
            color: #fff;
            background-color: #000; 
            padding: 8px; 
            border-radius: 5px;
            border: 1px solid #ccc; 
        }
        input[type="text"]:focus, 
        input[type="number"]:focus, 
        input[type="email"]:focus, 
        input[type="password"]:focus,
        input[type="url"]:focus {
            border-color: #4CAF50;
            outline: none; 
        }
        input[type="submit"] {
            color: antiquewhite;
            background-color: #4CAF50;
            border: none;
            padding: 10px 20px; 
            border-radius: 5px; 
            cursor: pointer;
            transition: background-color 0.3s; 
        }
        input[type="submit"]:hover {
            background-color: #45a049; 
        }
        h3 {
            margin-bottom: 20px;
        }
    </style>
</head>

<body>
    <div class="bg-black">
        <div style="margin-top: 150px;" class="main-container">
            <h3>Edit Product</h3>
            <hr>
            <div class="forms">
                <form method="POST">
                    {% csrf_token %}
                    <table>
                        {{ form.as_table }}
                        <tr>
                            <td></td>
                            <td>
                                <input type="submit" value="Edit Product"/>
                            </td>
                        </tr>
                    </table>
                </form>
            </div>
        </div>
        <h5 style="margin-top: 50px;">© Toko Wee | All rights Reserved.</h5>
        <h5>Nama: Arzaka Raffan Mawardi | NPM: 2306152393 | Kelas: PBP D</h5>
    </div>
</body>

{% endblock %}

main/templates/login.html
{% extends 'base.html' %}

{% block meta %}
<script src="https://cdn.jsdelivr.net/npm/dompurify@3.1.7/dist/purify.min.js"></script>
<title>Login</title>
{% endblock meta %}

{% block content %}
<!DOCTYPE html>
<html lang="en">
<head>
</head>
<body class="bg-black text-white font-sans">
    <div style="margin-top: 50px;" class="max-w-md mx-auto mt-24 bg-[rgb(25,25,25)] p-10 rounded-lg text-center">
        <img src="https://i.imgur.com/oTUETWx.png" class="mb-6 mx-auto">
        
        <form method="POST" action="">
            {% csrf_token %}
            <div class="mb-6 text-left">
                <label for="username" class="block text-lg font-semibold mb-2">Username</label>
                <input type="text" id="username" name="username" placeholder="Enter your username" required
                    class="w-full p-3 rounded-md bg-gray-700 text-white border-none focus:ring-2 focus:ring-gray-500" />
            </div>

            <div class="mb-6 text-left">
                <label for="password" class="block text-lg font-semibold mb-2">Password</label>
                <input type="password" id="password" name="password" placeholder="Enter your password" required
                    class="w-full p-3 rounded-md bg-gray-700 text-white border-none focus:ring-2 focus:ring-gray-500" />
            </div>

            <input class="w-full bg-gray-700 text-white rounded-lg py-3 font-bold cursor-pointer transition-transform transform hover:scale-105" type="submit" value="Login" />
        </form>

        {% if messages %}
        <ul class="mt-6 list-none">
            {% for message in messages %}
            <li class="text-red-400">{{ message }}</li>
            {% endfor %}
        </ul>
        {% endif %}
        
        <p class="mt-6">Don't have an account yet?</p>
        <a href="{% url 'main:register' %}" class="text-white font-bold hover:underline">Register Here!</a>
    </div>
</body>
</html>
{% endblock content %}

main/templates/main.html
{% extends 'base.html' %}
{% load static %}
{% block meta %}
<script src="https://cdn.jsdelivr.net/npm/dompurify@3.1.7/dist/purify.min.js"></script>
<title>TokoWee</title>
{% endblock meta %}
{% block content %}

{% include 'navbar.html' %}
<head>
    <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@400;600&display=swap" rel="stylesheet">
    <style>
        #crudModalContent {
            max-height: 90vh;
            overflow-y: auto;
        }
    </style>
</head>
<div class="bg-black min-h-screen font-poppins overflow-hidden">
    <div class="container mx-auto px-4 py-6 max-w-7xl pt-32">
        <div id="product_cards"></div>
    </div>
    <div id="crudModal" tabindex="-1" aria-hidden="true" class="hidden fixed inset-0 z-50 w-full flex items-center justify-center bg-gray-800 bg-opacity-50 overflow-x-hidden overflow-y-auto transition-opacity duration-300 ease-out">
        <div id="crudModalContent" class="relative bg-[rgb(25,25,25)] rounded-lg shadow-lg w-4/5 sm:w-3/4 md:w-2/3 lg:w-2/5 mx-4 sm:mx-0 transform scale-95 opacity-0 transition-transform transition-opacity duration-300 ease-out">
            <div class="flex items-center justify-between p-4 border-b rounded-t">
                <h3 class="text-xl font-semibold text-gray-900">
                    Add New Product
                </h3>
                <button type="button" class="text-gray-400 bg-transparent hover:bg-gray-200 hover:text-gray-900 rounded-lg text-sm p-1.5 ml-auto inline-flex items-center" id="closeModalBtn">
                    <svg aria-hidden="true" class="w-5 h-5" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg">
                        <path fill-rule="evenodd" d="M4.293 4.293a1 1 0 011.414 0L10 8.586l4.293-4.293a1 1 0 111.414 1.414L11.414 10l4.293 4.293a1 1 0 01-1.414 1.414L10 11.414l-4.293 4.293a1 1 0 01-1.414-1.414L8.586 10 4.293 5.707a1 1 0 010-1.414z" clip-rule="evenodd"></path>
                    </svg>
                    <span class="sr-only">Close modal</span>
                </button>
            </div>
            <div class="px-6 py-4 space-y-6 form-style">
                <form id="productForm">
                    <div class="mb-4">
                        <label for="itemName" class="block text-sm font-medium text-white">Item Name</label>
                        <input type="text" id="itemName" name="itemName" class="mt-1 block w-full border border-gray-300 rounded-md p-2 hover:border-indigo-700" placeholder="Enter item name" required>
                    </div>
                    <div class="mb-4">
                        <label for="itemDescription" class="block text-sm font-medium text-white">Item Description</label>
                        <textarea id="itemDescription" name="itemDescription" rows="3" class="mt-1 block w-full h-52 resize-none border border-gray-300 rounded-md p-2 hover:border-indigo-700" placeholder="Describe your item" required></textarea>
                    </div>
                    <div class="mb-4">
                        <label for="itemPrice" class="block text-sm font-medium text-white">Item Price ($)</label>
                        <input type="number" id="itemPrice" name="itemPrice" min="1" max="10000000000000000" class="mt-1 block w-full border border-gray-300 rounded-md p-2 hover:border-indigo-700" required>
                    </div>
                    <div class="mb-4">
                        <label for="itemStock" class="block text-sm font-medium text-white">Item Stock</label>
                        <input type="number" id="itemStock" name="itemStock" min="1" max="10000000000000000" class="mt-1 block w-full border border-gray-300 rounded-md p-2 hover:border-indigo-700" required>
                    </div>
                    <div class="mb-4">
                        <label for="itemCategory" class="block text-sm font-medium text-white">Item Category</label>
                        <textarea id="itemCategory" name="itemCategory" rows="3" class="mt-1 block w-full h-52 resize-none border border-gray-300 rounded-md p-2 hover:border-indigo-700" placeholder="Product Category" required></textarea>
                    </div>
                    <div class="mb-4">
                        <label for="itemImageURL" class="block text-sm font-medium text-white">Item IMG URL</label>
                        <textarea id="itemImageURL" name="itemImageURL" rows="3" class="mt-1 block w-full h-52 resize-none border border-gray-300 rounded-md p-2 hover:border-indigo-700" placeholder="Image URL" required>https://i.imgur.com/tGd7up6.jpeg</textarea>
                    </div>
                </form>
            </div>
            <div class="flex flex-col space-y-2 md:flex-row md:space-y-0 md:space-x-2 p-6 border-t border-gray-200 rounded-b justify-center md:justify-end">
                <button type="button" class="bg-gray-500 hover:bg-gray-600 text-white font-bold py-2 px-4 rounded-lg" id="cancelButton">Cancel</button>
                <button type="submit" id="submitProduct" form="productForm" class="bg-indigo-700 hover:bg-indigo-600 text-white font-bold py-2 px-4 rounded-lg">Save</button>
            </div>
        </div>
    </div>

    <div class="add-product text-center mt-5 pt-16 flex justify-center gap-4">
        <a href="{% url 'main:create_product' %}">
            <button class="bg-[rgb(25,25,25)] text-amber-50 rounded-lg py-2 px-4 font-bold transition-transform duration-500 transform hover:scale-105">
                Add a New Product
            </button>
        </a>
        <button data-modal-target="crudModal" data-modal-toggle="crudModal" class="bg-[rgb(25,25,25)] text-amber-50 rounded-lg py-2 px-4 font-bold transition-transform duration-500 transform hover:scale-105" onclick="showModal();">
            Add New Product by AJAX
        </button>
    </div>
    {% if last_login %}
    <h5 style="margin-top: 40px;" class="text-center text-white font-semibold mb-4">Last Login Session: {{ last_login }}</h5>
    {% else %}
    <h5 class="text-center text-white font-semibold mb-4">Last Login Session: No data available</h5>
    {% endif %}
    <h5 class="text-center text-white font-semibold mb-4">© Toko Wee | All rights Reserved.</h5>
    <h5 class="text-center text-white font-semibold mb-4">Nama: Arzaka Raffan Mawardi | NPM: 2306152393 | Kelas: PBP D</h5>
    <br>
</div>
<script>
    async function getProductEntries(){
        return fetch("{% url 'main:show_json' %}").then((res) => res.json())
    }
    async function refreshProductEntries() {
        document.getElementById("product_cards").innerHTML = "";
        document.getElementById("product_cards").className = "";
        const productEntries = await getProductEntries();
        let htmlString = "";
        let classNameString = "";
        if(productEntries.length === 0){
            classNameString = ""
            htmlString =`
            <img style="max-width: 500px; max-height: 500px; margin-top: 75px; margin-left: 382px;" src="{% static 'image/noprod.png' %}" alt="Sad face">
            `;
        }else{
            classNameString = "mt-6";
            productEntries.forEach((item) => {
                const name = DOMPurify.sanitize(item.fields.itemName);
                const price = DOMPurify.sanitize(item.fields.itemPrice);
                const description = DOMPurify.sanitize(item.fields.itemDescription);
                const stock = DOMPurify.sanitize(item.fields.itemStock);
                const category = DOMPurify.sanitize(item.fields.itemCategory);
                const link = DOMPurify.sanitize(item.fields.itemImageURL);
                htmlString += 
            `
                <div class="w-full max-w-[1100px] bg-[rgb(209,176,134)] rounded-2xl p-8 mx-auto flex mt-8">
                    <img src="${link}" alt="${name}" class="ml-5 rounded-xl w-72 h-72 object-cover transform transition-transform duration-500 hover:scale-105">
                    <div class="ml-12 flex-1 text-black flex flex-col justify-between">
                        <div class="text-center">
                            <h2 class="text-xl font-bold mb-3">${name}</h2>
                            <hr class="my-4 border-gray-300">
                        </div>
                        <h4 style="margin-top: -15px;" class="font-semibold">Price: $${price}</h4>
                        <h4 class="font-semibold mt-4">Description:</h4>
                        <pre class="text-sm font-medium mt-2 ml-4">${description}</pre>
                        <div class="mt-6">
                            <h4 class="font-semibold">Stock: ${stock} items</h4>
                            <h4 class="font-semibold mt-2">Category: ${category}</h4>
                        </div>
                        <div style="position: absolute; align-self: flex-end; margin-top: 200px;">
                            <a style="margin-bottom: 20px;" href="/edit/${item.pk}" class="flex items-center justify-center w-10 h-10">
                                <img src="https://i.imgur.com/69uZ2rc.png" alt="Edit" class="w-8 h-8 transition-transform duration-300 hover:scale-110">
                            </a>
                            <a href="/delete/${item.pk}" class="flex items-center justify-center w-10 h-10">
                                <img src="https://i.imgur.com/3BzlOY0.png" alt="Delete" class="w-8 h-8 transition-transform duration-300 hover:scale-110">
                            </a>
                        </div>
                    </div>
                </div>
            `;
            });
        }
        document.getElementById("product_cards").className = classNameString;
        document.getElementById("product_cards").innerHTML = htmlString;
    }

    refreshProductEntries();

    const modal = document.getElementById('crudModal');
    const modalContent = document.getElementById('crudModalContent');

    function showModal() {
        const modal = document.getElementById('crudModal');
        const modalContent = document.getElementById('crudModalContent');

        modal.classList.remove('hidden'); 
        setTimeout(() => {
            modalContent.classList.remove('opacity-0', 'scale-95');
            modalContent.classList.add('opacity-100', 'scale-100');
        }, 50); 
    }
    function hideModal() {
      const modal = document.getElementById('crudModal');
      const modalContent = document.getElementById('crudModalContent');

      modalContent.classList.remove('opacity-100', 'scale-100');
      modalContent.classList.add('opacity-0', 'scale-95');

      setTimeout(() => {
        modal.classList.add('hidden');
      }, 150); 
    }

    document.getElementById("cancelButton").addEventListener("click", hideModal);
    document.getElementById("closeModalBtn").addEventListener("click", hideModal);

    function addProduct() {
    fetch("{% url 'main:add_product_ajax' %}", {
      method: "POST",
      body: new FormData(document.querySelector('#productForm')),
    })
    .then(response => refreshProductEntries())

    document.getElementById("productForm").reset(); 
    hideModal();
    
    return false;
    }

    document.getElementById("productForm").addEventListener("submit", (e) => {
    e.preventDefault();
    addProduct();
    })
</script>
{% endblock content %}

main/templates/product_card.html
<div class="w-full max-w-[1100px] bg-[rgb(209,176,134)] rounded-2xl p-8 mx-auto flex">
    <img src="{{ product.itemImageURL }}" alt="{{ product.itemName }}" class="ml-5 rounded-xl w-72 h-72 object-cover transform transition-transform duration-500 hover:scale-105">
    <div class="ml-12 flex-1 text-black flex flex-col justify-between">
        <div class="text-center">
            <h2 class="text-xl font-bold mb-3">{{ product.itemName }}</h2>
            <hr class="my-4 border-gray-300">
        </div>
        <h4 style="margin-top: -15px;" class="font-semibold">Price: Rp {{ product.itemPrice }}</h4>
        <h4 class="font-semibold mt-4">Description:</h4>
        <pre class="text-sm font-medium mt-2 ml-4">{{ product.itemDescription }}</pre>
        <div class="mt-6">
            <h4 class="font-semibold">Stock: {{ product.itemStock }} items</h4>
            <h4 class="font-semibold mt-2">Category: {{ product.itemCategory }}</h4>
        </div>
        <div style="position: absolute; align-self: flex-end; margin-top: 200px;">
            <a style="margin-bottom: 20px;" href="{% url 'main:edit' product.pk %}" class="flex items-center justify-center w-10 h-10">
                <img src="https://i.imgur.com/69uZ2rc.png" alt="Edit" class="w-8 h-8 transition-transform duration-300 hover:scale-110">
            </a>
            <a href="{% url 'main:delete' product.pk %}" class="flex items-center justify-center w-10 h-10">
                <img src="https://i.imgur.com/3BzlOY0.png" alt="Delete" class="w-8 h-8 transition-transform duration-300 hover:scale-110">
            </a>
        </div>
    </div>
</div>